[project]
name = "downgrader"
version = "0.1.1"
description = "An open-source replication of the RockstarNexus GTA SA Downgrader, providing automated downgrading and mod installation."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyside6>=6.10.2",
    "requests>=2.32.5",
]
